export const countriesFlag = [
  { code: "IN", label: "India", flag: "https://flagcdn.com/w40/in.png" },
  {
    code: "AE",
    label: "United Arab Emirates",
    flag: "https://flagcdn.com/w40/ae.png",
  },
  { code: "AF", label: "Afghanistan", flag: "https://flagcdn.com/w40/af.png" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    flag: "https://flagcdn.com/w40/ag.png",
  },
  { code: "AI", label: "Anguilla", flag: "https://flagcdn.com/w40/ai.png" },
  { code: "AL", label: "Albania", flag: "https://flagcdn.com/w40/al.png" },
  { code: "AM", label: "Armenia", flag: "https://flagcdn.com/w40/am.png" },
  { code: "AO", label: "Angola", flag: "https://flagcdn.com/w40/ao.png" },
  { code: "AR", label: "Argentina", flag: "https://flagcdn.com/w40/ar.png" },
  {
    code: "AS",
    label: "American Samoa",
    flag: "https://flagcdn.com/w40/as.png",
  },
  { code: "AT", label: "Austria", flag: "https://flagcdn.com/w40/at.png" },
  { code: "AU", label: "Australia", flag: "https://flagcdn.com/w40/au.png" },
  { code: "AW", label: "Aruba", flag: "https://flagcdn.com/w40/aw.png" },
  { code: "AZ", label: "Azerbaijan", flag: "https://flagcdn.com/w40/az.png" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/w40/ba.png",
  },
  { code: "BB", label: "Barbados", flag: "https://flagcdn.com/w40/bb.png" },
  { code: "BD", label: "Bangladesh", flag: "https://flagcdn.com/w40/bd.png" },
  { code: "BE", label: "Belgium", flag: "https://flagcdn.com/w40/be.png" },
  { code: "BF", label: "Burkina Faso", flag: "https://flagcdn.com/w40/bf.png" },
  { code: "BG", label: "Bulgaria", flag: "https://flagcdn.com/w40/bg.png" },
  { code: "BH", label: "Bahrain", flag: "https://flagcdn.com/w40/bh.png" },
  { code: "BI", label: "Burundi", flag: "https://flagcdn.com/w40/bi.png" },
  { code: "BJ", label: "Benin", flag: "https://flagcdn.com/w40/bj.png" },
  { code: "BN", label: "Brunei", flag: "https://flagcdn.com/w40/bn.png" },
  { code: "BO", label: "Bolivia", flag: "https://flagcdn.com/w40/bo.png" },
  { code: "BR", label: "Brazil", flag: "https://flagcdn.com/w40/br.png" },
  { code: "BS", label: "Bahamas", flag: "https://flagcdn.com/w40/bs.png" },
  { code: "BT", label: "Bhutan", flag: "https://flagcdn.com/w40/bt.png" },
  { code: "BW", label: "Botswana", flag: "https://flagcdn.com/w40/bw.png" },
  { code: "BY", label: "Belarus", flag: "https://flagcdn.com/w40/by.png" },
  { code: "BZ", label: "Belize", flag: "https://flagcdn.com/w40/bz.png" },
  { code: "CA", label: "Canada", flag: "https://flagcdn.com/w40/ca.png" },
  { code: "CD", label: "Congo [DRC]", flag: "https://flagcdn.com/w40/cd.png" },
  {
    code: "CF",
    label: "Central African Republic",
    flag: "https://flagcdn.com/w40/cf.png",
  },
  {
    code: "CG",
    label: "Congo [Republic]",
    flag: "https://flagcdn.com/w40/cg.png",
  },
  { code: "CH", label: "Switzerland", flag: "https://flagcdn.com/w40/ch.png" },
  {
    code: "CI",
    label: "Côte d'Ivoire",
    flag: "https://flagcdn.com/w40/ci.png",
  },
  { code: "CL", label: "Chile", flag: "https://flagcdn.com/w40/cl.png" },
  { code: "CM", label: "Cameroon", flag: "https://flagcdn.com/w40/cm.png" },
  { code: "CN", label: "China", flag: "https://flagcdn.com/w40/cn.png" },
  { code: "CO", label: "Colombia", flag: "https://flagcdn.com/w40/co.png" },
  { code: "CR", label: "Costa Rica", flag: "https://flagcdn.com/w40/cr.png" },
  { code: "CU", label: "Cuba", flag: "https://flagcdn.com/w40/cu.png" },
  { code: "CY", label: "Cyprus", flag: "https://flagcdn.com/w40/cy.png" },
  {
    code: "CZ",
    label: "Czech Republic",
    flag: "https://flagcdn.com/w40/cz.png",
  },
  { code: "DE", label: "Germany", flag: "https://flagcdn.com/w40/de.png" },
  { code: "DK", label: "Denmark", flag: "https://flagcdn.com/w40/dk.png" },
  { code: "DM", label: "Dominica", flag: "https://flagcdn.com/w40/dm.png" },
  {
    code: "DO",
    label: "Dominican Republic",
    flag: "https://flagcdn.com/w40/do.png",
  },
  { code: "DZ", label: "Algeria", flag: "https://flagcdn.com/w40/dz.png" },
  { code: "EC", label: "Ecuador", flag: "https://flagcdn.com/w40/ec.png" },
  { code: "EE", label: "Estonia", flag: "https://flagcdn.com/w40/ee.png" },
  { code: "EG", label: "Egypt", flag: "https://flagcdn.com/w40/eg.png" },

  {
    code: "EH",
    label: "Western Sahara",
    flag: "https://flagcdn.com/w40/eh.png",
  },
  { code: "ER", label: "Eritrea", flag: "https://flagcdn.com/w40/er.png" },
  { code: "ET", label: "Ethiopia", flag: "https://flagcdn.com/w40/et.png" },
  { code: "ES", label: "Spain", flag: "https://flagcdn.com/w40/es.png" },
  { code: "FI", label: "Finland", flag: "https://flagcdn.com/w40/fi.png" },
  { code: "FJ", label: "Fiji", flag: "https://flagcdn.com/w40/fj.png" },
  {
    code: "FK",
    label: "Falkland Islands",
    flag: "https://flagcdn.com/w40/fk.png",
  },
  { code: "FM", label: "Micronesia", flag: "https://flagcdn.com/w40/fm.png" },
  {
    code: "FO",
    label: "Faroe Islands",
    flag: "https://flagcdn.com/w40/fo.png",
  },
  { code: "FR", label: "France", flag: "https://flagcdn.com/w40/fr.png" },
  { code: "GA", label: "Gabon", flag: "https://flagcdn.com/w40/ga.png" },
  {
    code: "GE",
    label: "United Kingdom",
    flag: "https://flagcdn.com/w40/ge.png",
  },
  { code: "GF", label: "Grenada", flag: "https://flagcdn.com/w40/gf.png" },

  { code: "GE", label: "Georgia", flag: "https://flagcdn.com/w40/ge.png" },
  {
    code: "GF",
    label: "French Guiana",
    flag: "https://flagcdn.com/w40/gf.png",
  },
  { code: "GG", label: "Guernsey", flag: "https://flagcdn.com/w40/gg.png" },
  { code: "GH", label: "Ghana", flag: "https://flagcdn.com/w40/gh.png" },
  { code: "GI", label: "Gibraltar", flag: "https://flagcdn.com/w40/gi.png" },
  { code: "GL", label: "Greenland", flag: "https://flagcdn.com/w40/gl.png" },
  { code: "GM", label: "Gambia", flag: "https://flagcdn.com/w40/gm.png" },
  { code: "GN", label: "Guinea", flag: "https://flagcdn.com/w40/gn.png" },
  { code: "GP", label: "Guadeloupe", flag: "https://flagcdn.com/w40/gp.png" },
  {
    code: "GQ",
    label: "Equatorial Guinea",
    flag: "https://flagcdn.com/w40/gq.png",
  },
  { code: "GR", label: "Greece", flag: "https://flagcdn.com/w40/gr.png" },
  {
    code: "GS",
    label: "South Georgia ",
    flag: "https://flagcdn.com/w40/gs.png",
  },
  { code: "GU", label: "Guam", flag: "https://flagcdn.com/w40/gU.png" },

  {
    code: "GW",
    label: "Guinea-Bissau",
    flag: "https://flagcdn.com/w40/gw.png",
  },
  { code: "GY", label: "Guyana", flag: "https://flagcdn.com/w40/gy.png" },
  { code: "GZ", label: "Gaza Strip", flag: "https://flagcdn.com/w40/gz.png" },
  { code: "HK", label: "Hong Kong", flag: "https://flagcdn.com/w40/hk.png" },
  { code: "HM", label: "Honduras", flag: "https://flagcdn.com/w40/hm.png" },
  { code: "HT", label: "Haiti", flag: "https://flagcdn.com/w40/ht.png" },
  { code: "HU", label: "Hungary", flag: "https://flagcdn.com/w40/hu.png" },
  { code: "ID", label: "Indonesia", flag: "https://flagcdn.com/w40/id.png" },
  { code: "IE", label: "Ireland", flag: "https://flagcdn.com/w40/ie.png" },
  { code: "IL", label: "Israel", flag: "https://flagcdn.com/w40/il.png" },
  { code: "IM", label: "Isle of Man", flag: "https://flagcdn.com/w40/im.png" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    flag: "https://flagcdn.com/w40/io.png",
  },

  { code: "IQ", label: "Iraq", flag: "https://flagcdn.com/w40/iq.png" },
  { code: "IR", label: "Iran", flag: "https://flagcdn.com/w40/ir.png" },
  { code: "IS", label: "Iceland", flag: "https://flagcdn.com/w40/is.png" },
  { code: "IT", label: "Italy", flag: "https://flagcdn.com/w40/it.png" },
  { code: "JE", label: "Jersey", flag: "https://flagcdn.com/w40/je.png" },
  { code: "JM", label: "Jamaica", flag: "https://flagcdn.com/w40/jm.png" },
  { code: "JO", label: "Jordan", flag: "https://flagcdn.com/w40/jo.png" },
  { code: "JP", label: "Japan", flag: "https://flagcdn.com/w40/jp.png" },
  { code: "KE", label: "Kenya", flag: "https://flagcdn.com/w40/ke.png" },
  { code: "KG", label: "Kyrgyzstan", flag: "https://flagcdn.com/w40/kg.png" },
  { code: "KH", label: "Cambodia", flag: "https://flagcdn.com/w40/kh.png" },
  { code: "KI", label: "Kiribati ", flag: "https://flagcdn.com/w40/ki.png" },
  { code: "KM", label: "Comoros", flag: "https://flagcdn.com/w40/km.png" },

  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/w40/kn.png",
  },
  { code: "KP", label: "North Korea", flag: "https://flagcdn.com/w40/kp.png" },
  { code: "KR", label: "South Korea", flag: "https://flagcdn.com/w40/kr.png" },
  { code: "KW", label: "Kuwait", flag: "https://flagcdn.com/w40/kw.png" },
  {
    code: "KY",
    label: "Cayman Islands",
    flag: "https://flagcdn.com/w40/ky.png",
  },
  { code: "KZ", label: "Kazakhstan", flag: "https://flagcdn.com/w40/kz.png" },
  { code: "LA", label: "Laos", flag: "https://flagcdn.com/w40/la.png" },
  { code: "LB", label: "Lebanon", flag: "https://flagcdn.com/w40/lb.png" },
  { code: "LC", label: "Saint Lucia", flag: "https://flagcdn.com/w40/lc.png" },
  {
    code: "LI",
    label: "Liechtenstein",
    flag: "https://flagcdn.com/w40/li.png",
  },
  { code: "LK", label: "Sri Lanka", flag: "https://flagcdn.com/w40/lk.png" },
  { code: "LR", label: "Liberia ", flag: "https://flagcdn.com/w40/lr.png" },
  { code: "LS", label: "Lesotho", flag: "https://flagcdn.com/w40/ls.png" },

  { code: "LT", label: "Lithuania", flag: "https://flagcdn.com/w40/lt.png" },
  { code: "LU", label: "Luxembourg", flag: "https://flagcdn.com/w40/lu.png" },
  { code: "LV", label: "Latvia", flag: "https://flagcdn.com/w40/lv.png" },
  { code: "LY", label: "Libya", flag: "https://flagcdn.com/w40/ly.png" },
  { code: "MA", label: "Morocco", flag: "https://flagcdn.com/w40/ma.png" },
  { code: "MC", label: "Monaco", flag: "https://flagcdn.com/w40/mc.png" },
  { code: "MD", label: "Moldova", flag: "https://flagcdn.com/w40/md.png" },
  { code: "ME", label: "Montenegro", flag: "https://flagcdn.com/w40/me.png" },
  { code: "MG", label: "Madagascar", flag: "https://flagcdn.com/w40/mg.png" },
  {
    code: "MH",
    label: "Marshall Islands",
    flag: "https://flagcdn.com/w40/mh.png",
  },
  { code: "MK", label: "Macedonia", flag: "https://flagcdn.com/w40/mk.png" },
  { code: "ML", label: "Mali ", flag: "https://flagcdn.com/w40/ml.png" },
  { code: "MM", label: "Myanmar", flag: "https://flagcdn.com/w40/mm.png" },

  { code: "MN", label: "Mongolia", flag: "https://flagcdn.com/w40/mn.png" },
  { code: "MO", label: "Macau", flag: "https://flagcdn.com/w40/mo.png" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    flag: "https://flagcdn.com/w40/mp.png",
  },
  { code: "MQ", label: "Martinique", flag: "https://flagcdn.com/w40/mq.png" },
  { code: "MR", label: "Mauritania", flag: "https://flagcdn.com/w40/mr.png" },
  { code: "MS", label: "Montserrat", flag: "https://flagcdn.com/w40/ms.png" },
  { code: "MT", label: "Malta", flag: "https://flagcdn.com/w40/mt.png" },
  { code: "MU", label: "Mauritius", flag: "https://flagcdn.com/w40/mu.png" },
  { code: "MV", label: "Maldives", flag: "https://flagcdn.com/w40/mv.png" },
  { code: "MW", label: "Malawi ", flag: "https://flagcdn.com/w40/mw.png" },
  { code: "MX", label: "Mexico", flag: "https://flagcdn.com/w40/mx.png" },
  { code: "MY", label: "Malaysia ", flag: "https://flagcdn.com/w40/my.png" },
  { code: "MZ", label: "Mozambique", flag: "https://flagcdn.com/w40/mz.png" },

  { code: "NA", label: "Namibia", flag: "https://flagcdn.com/w40/na.png" },
  {
    code: "NC",
    label: "New Caledonia",
    flag: "https://flagcdn.com/w40/nc.png",
  },
  { code: "NE", label: "Niger", flag: "https://flagcdn.com/w40/ne.png" },
  {
    code: "NF",
    label: "Norfolk Island",
    flag: "https://flagcdn.com/w40/nf.png",
  },
  { code: "NG", label: "Nigeria", flag: "https://flagcdn.com/w40/ng.png" },
  { code: "NI", label: "Nicaragua", flag: "https://flagcdn.com/w40/ni.png" },
  { code: "NL", label: "Netherlands", flag: "https://flagcdn.com/w40/nl.png" },
  { code: "NO", label: "Norway", flag: "https://flagcdn.com/w40/no.png" },
  { code: "NP", label: "Nepal", flag: "https://flagcdn.com/w40/np.png" },
  { code: "NR", label: "Nauru ", flag: "https://flagcdn.com/w40/nr.png" },
  { code: "NU", label: "Niue", flag: "https://flagcdn.com/w40/nu.png" },
  { code: "NZ", label: "New Zealand ", flag: "https://flagcdn.com/w40/nz.png" },
  { code: "OM", label: "Oman", flag: "https://flagcdn.com/w40/om.png" },

  { code: "PA", label: "Panama", flag: "https://flagcdn.com/w40/pa.png" },
  { code: "PE", label: "Peru", flag: "https://flagcdn.com/w40/pe.png" },
  {
    code: "PF",
    label: "French Polynesia",
    flag: "https://flagcdn.com/w40/pf.png",
  },
  {
    code: "PG",
    label: "Papua New Guinea",
    flag: "https://flagcdn.com/w40/pg.png",
  },
  { code: "PH", label: "Philippines", flag: "https://flagcdn.com/w40/ph.png" },
  { code: "PK", label: "Pakistan", flag: "https://flagcdn.com/w40/pk.png" },
  { code: "PL", label: "Poland", flag: "https://flagcdn.com/w40/pl.png" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/w40/pm.png",
  },
  {
    code: "PN",
    label: "Pitcairn Islands",
    flag: "https://flagcdn.com/w40/pn.png",
  },
  { code: "PR", label: "Puerto Rico ", flag: "https://flagcdn.com/w40/pr.png" },
  {
    code: "PS",
    label: "Palestinian Territories",
    flag: "https://flagcdn.com/w40/ps.png",
  },
  { code: "PT", label: "Portugal ", flag: "https://flagcdn.com/w40/pt.png" },
  { code: "PW", label: "Palau", flag: "https://flagcdn.com/w40/pw.png" },

  { code: "PY", label: "Paraguay", flag: "https://flagcdn.com/w40/py.png" },
  { code: "QA", label: "Qatar", flag: "https://flagcdn.com/w40/qa.png" },
  { code: "RE", label: "Réunion", flag: "https://flagcdn.com/w40/re.png" },
  { code: "RO", label: "Romania", flag: "https://flagcdn.com/w40/ro.png" },
  { code: "RS", label: "Serbia", flag: "https://flagcdn.com/w40/rs.png" },
  { code: "RU", label: "Russia", flag: "https://flagcdn.com/w40/ru.png" },
  { code: "RW", label: "Rwanda", flag: "https://flagcdn.com/w40/rw.png" },
  { code: "SA", label: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png" },
  {
    code: "SB",
    label: "Solomon Islands",
    flag: "https://flagcdn.com/w40/sb.png",
  },
  { code: "SC", label: "Seychelles ", flag: "https://flagcdn.com/w40/sc.png" },
  { code: "SD", label: "Sudan", flag: "https://flagcdn.com/w40/sd.png" },
  { code: "SE", label: "Sweden ", flag: "https://flagcdn.com/w40/se.png" },
  { code: "SG", label: "Singapore", flag: "https://flagcdn.com/w40/sg.png" },

  { code: "SH", label: "Saint Helena", flag: "https://flagcdn.com/w40/sh.png" },
  { code: "SL", label: "Slovenia", flag: "https://flagcdn.com/w40/sl.png" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    flag: "https://flagcdn.com/w40/sj.png",
  },
  { code: "SK", label: "Slovakia", flag: "https://flagcdn.com/w40/sk.png" },
  { code: "SL", label: "Sierra Leone", flag: "https://flagcdn.com/w40/sl.png" },
  { code: "SM", label: "San Marino", flag: "https://flagcdn.com/w40/sm.png" },
  { code: "SN", label: "Senegal", flag: "https://flagcdn.com/w40/sn.png" },
  { code: "SO", label: "Somalia", flag: "https://flagcdn.com/w40/so.png" },
  { code: "SR", label: "Suriname", flag: "https://flagcdn.com/w40/sr.png" },
  {
    code: "St",
    label: "São Tomé and Príncipe ",
    flag: "https://flagcdn.com/w40/st.png",
  },
  { code: "SV", label: "El Salvador", flag: "https://flagcdn.com/w40/sv.png" },
  { code: "SY", label: "Syria ", flag: "https://flagcdn.com/w40/sy.png" },
  { code: "SZ", label: "Swaziland", flag: "https://flagcdn.com/w40/sz.png" },

  {
    code: "TC",
    label: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/w40/tc.png",
  },
  { code: "TD", label: "Chad", flag: "https://flagcdn.com/w40/td.png" },
  {
    code: "TF",
    label: "French Southern Territories",
    flag: "https://flagcdn.com/w40/tf.png",
  },
  { code: "TG", label: "Togo", flag: "https://flagcdn.com/w40/tg.png" },
  { code: "TH", label: "Thailand", flag: "https://flagcdn.com/w40/th.png" },
  { code: "TJ", label: "Tajikistan", flag: "https://flagcdn.com/w40/tj.png" },
  { code: "TK", label: "Tokelau", flag: "https://flagcdn.com/w40/tk.png" },
  { code: "TL", label: "Timor-Leste", flag: "https://flagcdn.com/w40/tl.png" },
  { code: "TM", label: "Turkmenistan", flag: "https://flagcdn.com/w40/tm.png" },
  { code: "TN", label: "Tunisia", flag: "https://flagcdn.com/w40/tn.png" },
  { code: "TO", label: "Tonga", flag: "https://flagcdn.com/w40/to.png" },
  { code: "TR", label: "Turkey ", flag: "https://flagcdn.com/w40/tr.png" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    flag: "https://flagcdn.com/w40/tt.png",
  },

  { code: "TV", label: "Tuvalu", flag: "https://flagcdn.com/w40/tv.png" },
  { code: "TW", label: "Taiwan", flag: "https://flagcdn.com/w40/tw.png" },
  { code: "TZ", label: "Tanzania", flag: "https://flagcdn.com/w40/tz.png" },
  { code: "UA", label: "Ukraine", flag: "https://flagcdn.com/w40/ua.png" },
  { code: "UG", label: "Uganda", flag: "https://flagcdn.com/w40/ug.png" },
  {
    code: "UM",
    label: "U.S. Minor Outlying Islands",
    flag: "https://flagcdn.com/w40/um.png",
  },
  {
    code: "US",
    label: "United States",
    flag: "https://flagcdn.com/w40/us.png",
  },
  { code: "UY", label: "Uruguay", flag: "https://flagcdn.com/w40/uy.png" },
  { code: "UZ", label: "Uzbekistan", flag: "https://flagcdn.com/w40/uz.png" },
  { code: "VA", label: "Vatican City", flag: "https://flagcdn.com/w40/va.png" },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/w40/vc.png",
  },
  { code: "VE", label: "Venezuela ", flag: "https://flagcdn.com/w40/ve.png" },
  {
    code: "VG",
    label: "British Virgin Islands",
    flag: "https://flagcdn.com/w40/vg.png",
  },

  {
    code: "VI",
    label: "U.S. Virgin Islands",
    flag: "https://flagcdn.com/w40/vi.png",
  },
  { code: "VN", label: "Vietnam", flag: "https://flagcdn.com/w40/vn.png" },
  { code: "VU", label: "Vanuatu", flag: "https://flagcdn.com/w40/vu.png" },
  {
    code: "WF",
    label: "Wallis and Futuna",
    flag: "https://flagcdn.com/w40/wf.png",
  },
  { code: "WS", label: "Samoa", flag: "https://flagcdn.com/w40/ws.png" },
  { code: "XK", label: "Kosovo", flag: "https://flagcdn.com/w40/xk.png" },
  { code: "YE", label: "Yemen", flag: "https://flagcdn.com/w40/ye.png" },
  { code: "YT", label: "Mayotte", flag: "https://flagcdn.com/w40/yt.png" },
  { code: "ZA", label: "South Africa", flag: "https://flagcdn.com/w40/za.png" },
  { code: "ZM", label: "Zambia", flag: "https://flagcdn.com/w40/zm.png" },
  { code: "ZW", label: "Zimbabwe", flag: "https://flagcdn.com/w40/zw.png" },
];
