import { Router } from "express";
import authRoutes from "../../modules/auth";
import tenantRoutes from "../../modules/tenant";
import groupRoutes from "../../modules/group";
import leadRoutes from "../../modules/lead";
import organizationRoutes from "../../modules/organization";
import userRoutes from "../../modules/user";
import callRoutes from "../../modules/call";
import commentRoutes from "../../modules/comment";
import dealRoutes from "../../modules/deal";
import dashboardRoutes from "../../modules/dashboard";
import uploadRoutes from "../../modules/upload";
import attachmentRoutes from "../../modules/attachment";
import workflowRoutes from "../../modules/workflow";
import leadEmailRoutes from "../../modules/lead-email";
import webhookRoutes from "../../modules/webhook";
import emailTrackingRoutes from "../../modules/tracking";
import taskRoutes from "../../modules/task";
import langchainRoutes from "../../modules/langchain";
import emailTemplateRoutes from "../../modules/email-template";

export const router = Router();

router.use("/auth", authRoutes);
router.use("/tenant", tenantRoutes);
router.use("/lead", leadRoutes);
router.use("/organization", organizationRoutes);
router.use("/deal", dealRoutes);
router.use("/user", userRoutes);
router.use("/call", callRoutes);
router.use("/comment", commentRoutes);
router.use("/attachment", attachmentRoutes);
router.use("/email", leadEmailRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/group", groupRoutes);
router.use("/email-template", emailTemplateRoutes);
router.use("/upload", uploadRoutes);
router.use("/workflow", workflowRoutes);
router.use("/webhook", webhookRoutes);
router.use("/track", emailTrackingRoutes);
router.use("/task", taskRoutes);
router.use("/langchain", langchainRoutes);
